name = "crypto-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[env.production.vars]
DB_HOST = "srv787.hstgr.io"
DB_USER = "u208245805_Crypto21"
DB_NAME = "u208245805_Crypto21"

# Store sensitive data as secrets using: wrangler secret put DB_PASSWORD
# DB_PASSWORD will be available as env.DB_PASSWORD in your worker